monolog:
    handlers:
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

when@test:
    monolog:
        handlers:
            doctrine:
                channels : ['doctrine']
                type: stream
                path: "%kernel.logs_dir%/doctrine_%kernel.environment%.log"
                level: debug
                formatter: App\Service\Util\Log\DoctrineSqlFormatter

