services:

    nginx:
        container_name: factory_nginx
        build: ./.docker/nginx
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '5004:80'

    php:
        container_name: factory_php
        build: ./.docker/php
        volumes:
            - ./:/var/www/html

    mysql:
        container_name: factory_mysql
        build: ./.docker/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=factory"
            - "MYSQL_USER=factory"
            - "MYSQL_PASSWORD=factory"
        volumes:
            - db-data-factory:/var/lib/mysql
            - ./:/app
            - ./.docker/mysql/config/my.cnf:/etc/mysql/my.cnf
            #- ./.docker/mysql/data:/var/data/
        ports:
            - "33308:3306"

volumes:
    db-data-factory:
