parameters:
    api_url: '%env(API_URL)%'
services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'


